### ISSUE TITLE
Can't open sample program

### ISSUE THREAD

**Issue by miqbal23** [Windows-Readiness/WinDevCamp#2]
I got this errors when I tried to open the sample solution provided in the repo. Is it because my Visual Studio or is there something wrong?
![screenshot 11](https://cloud.githubusercontent.com/assets/12664445/10156602/297c7f3a-66ad-11e5-9425-37d16e5e1110.png)

**Comment by devanshi21897** [comment]
i also got something like that.

**Comment by miqbal23** [comment]
Ah sorry, I found the solution
For any of you having this issue, do this : 
1. Right-click the Solution name on Solution Explorer
2. Choose "Restore NuGet package", wait until done
3. Right-click again, but now choose "Clean Solution"
4. Re-build solution. After that, it should be fine
